### ISSUE TITLE
.xz file in data folder cannot be uncompressed

### ISSUE THREAD

**Issue by parphyam** [ChenxiSSS/FG21SimPlus#7]
Hi, 

 While trying to use the template data `Halpha_fwhm06_ns1024.fits.xz`, `synchrotron_specind2_ns512.fits.xz`, `haslam408_dsds_Remazeilles2014_ns512.fits.xz`, I am getting a `data not recognised` error while trying `xz -d <file_name.xz>` from a linux machine. Similarly, in a Mac, I am getting `unsupported format` while extracting with Archive utilities. Any insights on the reason for this and how to extract the data?

**Comment by ChenxiSSS** [comment]
Hi,

Not sure if the data are downloaded properly. You can follow our latest data guide here: https://github.com/Fg21Sim/Data/blob/main/README.md

Best,
Chenxi

**Comment by parphyam** [comment]
Hi @ChenxiSSS, these files are working, thank you so much. Also, thanks for clearly indicating that the correct data are available via WeTransfer.
